### ISSUE TITLE
Error when posting article

### ISSUE THREAD

**Issue by th0rgall** [reallyreadit/db#5] opened 2022-06-14 08:07 UTC
But the post did seem to have succeeded anyway 
https://user-images.githubusercontent.com/11543641/173526911-ee78a85d-84a3-4655-bdd5-ded050c8275e.MOV

**Comment by th0rgall** [comment] 2022-09-01 21:48
I investigated this issue further in the last few days. It is a database issue appearing after the upgrade to Postgres v14 from v9.6. 

The Readup API error is returned as a 400 Bad Request HTTP code, which triggers the error screen in the Readup apps
<details>
<summary>The API app error log for this request</summary> 

```
2022-08-30 21:50:29.531 +00:00 [ERR] Failed to create new post.
Npgsql.PostgresException (0x80004005): XX000: AfterTriggerSaveEvent() called outside of query
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|211_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.<ReadMessage>g__ReadMessageSequential|44_0(NpgsqlConnector connector, Boolean async)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 418
   at api.Notifications.NotificationService.CreateLoopbackNotifications(Comment comment) in C:\Users\jeff\repos\reallyreadit\api\src\Notifications\NotificationService.cs:line 746
   at api.Commenting.CommentingService.PostComment(String text, Int64 articleId, UserAccount user, Boolean tweet, ClientAnalytics analytics) in C:\Users\jeff\repos\reallyreadit\api\src\Commenting\CommentingService.cs:line 96
   at api.Controllers.Social.SocialController.Post(ObfuscationService obfuscationService, NotificationService notificationService, CommentingService commentingService, PostForm form) in C:\Users\jeff\repos\reallyreadit\api\src\Controllers\Social\SocialController.cs:line 534
  Exception data:
    Severity: ERROR
    SqlState: XX000
    MessageText: AfterTriggerSaveEvent() called outside of query
    Where: SQL function "create_loopback_notifications" statement 1
    File: trigger.c
    Line: 5488
    Routine: AfterTriggerSaveEvent
```

</details>

The actual error is thus in the **database**: "AfterTriggerSaveEvent() called outside of query".

## Database error

The database error occurs seemingly whenever the `create_loopback_notification`s function is called, and would be in a situation where it generates loopback notifications. I confirmed this using the sample database with two new accounts, which do not follow eachother. Both have read one sample article and post it. When the second reader posts the article, the error occurs.

Through experimenting with different Postgres versions (9.6, 12, 13, 14), it looks like **the error only occurs on Postgres v13 and v14.**

## Reproduction

This is a minimal db dump of a 9.6 database with two additional accounts added, which both read article G.

[loopback.dump.zip](https://github.com/reallyreadit/db/files/9473568/loopback.dump.zip)

To reproduce:
- Unzip the dump
- If not installed already, install Postgres v13 or v14 (easiest is just running the most current docker-compose db service via dev-env).
- Import the db dump with `pwsh dev-scripts/restore.ps1 rrit loopback.dump`
- Make sure the whole dev env is running with this db dump.
- Make sure the article test server is running.
- Start a Readup app (for example the the iOS simulator)
- Log in with the account `account2@email.com`, and password `12345678`
- Go to Contenders -> New. Article G should already be read by account2.
- Open the article, scroll down, then "Post again". This triggers the `create_loopback_notification` function call, which triggers the error.

With the same dump, the error can also be manually reproduced with the equivalent function call as would be produced by the API: `SELECT notifications.create_loopback_notifications(4, 5, 5);`

<img width="773" alt="Screenshot 2022-09-01 at 15 18 42" src="https://user-images.githubusercontent.com/11543641/188018772-0ce684ab-1dd2-4f65-9b0b-d21228c6ab33.png">


### References for the error
Some people have seen this error, but not on 13/14 and not in situations that seem to be related to the loopback notification function.

- answered, related to DEFERRABLE constraints 
  - https://postgrespro.com/list/thread-id/1506897
  - https://postgrespro.com/list/thread-id/2211228
- unanswered, related to replication https://www.mail-archive.com/pgsql-hackers@postgresql.org/msg302848.html

**Comment by jacamera** [comment] 2022-09-02 02:49
Think I got it! https://github.com/reallyreadit/db/commit/cc9bac9c2d5490a6f426a7a45b01bb96a89d59d8

**Comment by th0rgall** [comment] 2022-09-03 00:03
You did! I confirmed that running that migration makes the error go away on my reproduction case in Postgres v14. Epic fix.

For any googler ending up here, "AfterTriggerSaveEvent() called outside of query" can apparently be a misleading error message. @jacamera said about debugging this:

>  I was able to pinpoint it by starting to rewrite the function as a plpgsql function with individual statements. For some reason I got the correct type-mismatch error message after partially rewriting it and from there it was an easy fix.

**Comment by jacamera** [comment] 2022-09-03 01:47
Great! I'll close this issue then since you confirmed it and I ran the migration on the production database. My condolences to anyone searching for that error message! 😄

**Closed by jacamera** 2022-09-03 01:47 UTC
Labels: bug
